using EnergyInsightHub.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.VisualBasic.FileIO;

namespace EnergyInsightHub.Data;

public class EnergyHubContext : DbContext
{
    protected readonly IConfiguration Configuration;
    public EnergyHubContext(IConfiguration configuration)
    {
        Configuration = configuration;
        Database.EnsureCreated();
    }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder.UseSqlite(Configuration.GetConnectionString("EnergyHubDB"));
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Reading>()
                .Property(m => m.Id)
                .ValueGeneratedOnAdd(); // Id is generated by the database
    }

    public void ResetDB() {
        Readings.RemoveRange(Readings); // delete old readings
        var testData = ReadCsv("Data\\testData.csv");
        Readings.AddRange(testData); // add test readings
        SaveChangesAsync();
    }

    private List<Reading> ReadCsv(string filePath) {
        List<Reading> testReadings = new();

        using (TextFieldParser parser = new TextFieldParser(filePath)) {
            parser.TextFieldType = FieldType.Delimited;
            parser.SetDelimiters(",");

            parser.ReadFields(); // skip first row (headers)

            while (!parser.EndOfData) {
                string[] fields = parser.ReadFields();

                // Assuming CSV structure matches object properties
                Reading reading = new(){
                    EnergyMeterId = int.Parse(fields[0]),
                    MicrocontrollerId = int.Parse(fields[1]),
                    Time = DateTime.Parse(fields[2]),
                    Amount = decimal.Parse(fields[3])
                };

                testReadings.Add(reading);
            }
        }

        return testReadings;
    }

    public DbSet<Reading> Readings { get; set; }
}
